CXX = g++
EXEC = solarsystem
SOURCES = main.cpp SolarSystem.cpp
OBJECTS = main.o SolarSystem.o
LDFLAGS = -lglut -lGL -lGLU

all :
	$(CXX) $(SOURCES) $(LDFLAGS) -o $(EXEC)
clean:
	rm -f $(EXEC) *.gdc *.o


